apiVersion: v1
kind: Service

metadata:
  name: mailer-service
  labels:
    app: mailer-app

spec:
  selector:
    component: mailer-deployment

  ports:
  - protocol: TCP
    port: 8080                  
    targetPort: 8088 
  type: LoadBalancer
