apiVersion: apps/v1
kind: Deployment

metadata:
  name: mailer-data
  namespace: bdd-namespace

spec:

  selector:
    matchLabels:
      component: postgres-container

  template:
    metadata:
      labels:
        app: mailer-app
        component: postgres-container

    spec:
      containers:
      
        - name: postgres-container
          image: postgres:latest

          envFrom:
            - configMapRef:
                name: data-env-vars
            - secretRef:
                name: data-secrets

          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

          ports:
            - containerPort: 5432

          volumeMounts:
            - name: mailer-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: mailer-data
          persistentVolumeClaim:
            claimName: mailer-claim
