apiVersion: v1
kind: Service

metadata:
  name: bdd-cluster-ip
  namespace: bdd-namespace


spec:
  selector:
        component: postgres-container

  type: ClusterIP

  ports:
  - port: 5432
    targetPort: 5432