apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mailer-claim
  namespace: bdd-namespace
  labels:
    app: mailer-app


spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi